### ISSUE TITLE
Named Pipe performance drop going from 5.3.4 to 5.3.5

### ISSUE THREAD

**Issue by berk-csi** [tylerjensen/ServiceWire#56]
I noticed a significant performance drop in named pipes in **ServiceWire 5.3.5** and up. **ServiceWire 5.3.4** is nearly **3X** faster compared to 5.3.5 on the attached MRE.

To test, just run the tester console application referencing ServiceWire 5.3.4 twice, one in 'server' mode and one in 'client' mode. It'll time 5000 calls to a simple interface and report the average time over 5 runs. Repeat it again with the tester referencing ServiceWire 5.3.5.

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/101315025/169503415-139414ca-64f8-42d9-9616-de0f025c9223.png">

[TestIPC.zip](https://github.com/tylerjensen/ServiceWire/files/8738412/TestIPC.zip)

**Comment by tylerje** [comment]
Thanks for reporting the error. This has been fixed in version 5.4.2 which should be available on NuGet momentarily. The fix is on this line. 
https://github.com/tylerjensen/ServiceWire/blob/21f3a841302d0477d3309c2bce8c9edb5099cdf9/src/ServiceWire/NamedPipes/NpListener.cs#L101

If you review the history, you'll see that the package you found to work targeted .NET 4.62 and had a slightly different constructor for the NamedPipeServerStream. Taking the default values in the newer constructor without pushing through the transmission mode, options, and buffer size resulted in the extra time wasted on the pipe.

Thanks for bringing this to my attention.
